mode: immediate
# branchName: "${issue.number}-${process.env.BRANCH_NAME}"
branchName: "${issue.number}-${payload.comment.body}"

# mode: chatops
# experimental:
#   branchNameArgument: true

autoCloseIssue: true
openPR: false
# openDraftPR: true
# copyIssueLabelsToPR: true
# copyIssueAssigneeToPR: true
autoLinkIssue: true

branches:
  - label: "🐛 bug"
    prefix: bug/
  - label: "💫 feat"
    prefix: feat/
  - label: "🔥 hotfix"
    prefix: hotfix/
