# branchName: "${issue.number}-${process.env.BRANCH_NAME}"
branchName: "${issue.number}-aaaaa"
autoCloseIssue: true
# openDraftPR: true
# copyIssueLabelsToPR: true
# copyIssueAssigneeToPR: true
mode: immediate
openPR: false
# autoLinkIssue: false
branches:
  - label: "🐛 bug"
    prefix: bug/
  - label: "💫 feat"
    prefix: feat/
  - label: "🔥 hotfix"
    prefix: hotfix/
