branchName: "${issue.number}-${issue.title}"
autoCloseIssue: true
openDraftPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
mode: immediate
autoLinkIssue: false
branches:
  - label: "🐛 bug"
    prefix: bug/
  - label: "💫 feat"
    prefix: feat/
  - label: "🔥 hotfix"
    prefix: hotfix/
