branchName: "${issue.number}-${{ steps.step1.outputs.BRANCH_NAME }}"
autoCloseIssue: true
# openDraftPR: true
# copyIssueLabelsToPR: true
# copyIssueAssigneeToPR: true
mode: immediate
openPR: false
# autoLinkIssue: false
branches:
  - label: "🐛 bug"
    prefix: bug/
  - label: "💫 feat"
    prefix: feat/
  - label: "🔥 hotfix"
    prefix: hotfix/
